### ISSUE TITLE
Segmentation Fault when processing some .dim files in versions 5.3.4 and 5.3.6

### ISSUE THREAD

**Issue by emilioj** [bsc-performance-tools/dimemas#1]
Hi there!

Dimemas (v5.3.4 and v5.3.6) abruptly finishes with a SegFault when processing the .dim file obtained from `Iberia-128-CA.chop1.1it.shifted.prv` following the 'official' tutorial (_2.Introduction_to_Dimemas_):

```shell
emilioj@worlorn /opt/wxparaver-4.7.2-Linux_x86_64/tutorials/2.Introduction_to_Dimemas
 % ~/loads/dimemas-5.3.4-Linux_x86_64/bin/Dimemas -S 32K -p prediction.1ppn.prv MN.128.1ppn.cfg
-> Simulator configuration to be read MN.128.1ppn.cfg
-> Loading default random values
zsh: segmentation fault  ~/loads/dimemas-5.3.4-Linux_x86_64/bin/Dimemas -S 32K -p prediction.1ppn.prv
```
```shell
emilioj@worlorn /opt/wxparaver-4.7.2-Linux_x86_64/tutorials/2.Introduction_to_Dimemas
 % /opt/dimemas-5.3.6-Linux_x86_64/bin/Dimemas -S 32K -p prediction.1ppn.prv MN.128.1ppn.cfg
-> Simulator configuration to be read MN.128.1ppn.cfg
-> Loading default random values
zsh: segmentation fault  /opt/dimemas-5.3.6-Linux_x86_64/bin/Dimemas -S 32K -p prediction.1ppn.prv
```
That file, `Iberia-128-CA.chop1.1it.shifted.dim`, is processed Ok with previous versions (I tested 5.3.3, 5.3.2 and 5.3.0).

**Comment by loveshack** [comment]
I just found the same (on RHEL7).  I'm not confident enough to try to debug it but, for what it's worth, the commit which broke it is 4b33916228cd572751e764b560c9cf5c8da55e1e

**Comment by csktan** [comment]
Thank you for pointing out the bug. 
commit f602493 solves the issue. 

sorry for the delay
